# Generated by Django 4.1.7 on 2023-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STT', models.CharField(max_length=30)),
                ('Ten_cot', models.CharField(max_length=200)),
                ('Kieu_du_lieu', models.CharField(max_length=300)),
                ('Chu_thich', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Demo',
            },
        ),
    ]
